### ISSUE TITLE
Extract coordinates of nuclei in image

### ISSUE THREAD

**Issue by hossam-zaki** [histocartography/histocartography#12]
Hello!

Hope all is well. I have two images. One with the H+E staining, and another one, which is the exact same, but is colored by cell label. I'm wondering if it is possible to extract the coordinates of each nuclei in the input image? I would like to go from the nuclei in one picture to its label in the other using the coordinates. Is this possible?

See the two images below (this is from an open source dataset):

<img width="649" alt="Screen Shot 2021-06-10 at 11 40 33 PM" src="https://user-images.githubusercontent.com/55958261/121627391-40951b80-ca45-11eb-92fa-ae6cf81372fb.png">
<img width="649" alt="Screen Shot 2021-06-10 at 11 40 48 PM" src="https://user-images.githubusercontent.com/55958261/121627408-4985ed00-ca45-11eb-8e58-168d6ca0271d.png">

**Comment by hossam-zaki** [comment]
Hi! Thanks a lot for the response..

I ended up trying this out, but it outputted some centroids that were outside of the image, as seen in this screenshot. 
![Screen Shot 2021-06-17 at 5 03 34 PM](https://user-images.githubusercontent.com/55958261/122471977-f56f9100-cf8d-11eb-8c53-ac111018b6ac.png)

Any advice with this? Am I getting the centroids properly? Really appreciate your help!

**Comment by guillaumejaume** [comment]
Can you print the image size? 

Numpy and image-based packages use different indexing conventions, (row,col) for numpy and (x,y) for PIL, cv2 etc.

**Comment by hossam-zaki** [comment]
Sure. Check this out. 

I was thinking it could be reversed, but wanted to double check. Really appreciate your help!
![Screen Shot 2021-06-18 at 2 59 04 AM](https://user-images.githubusercontent.com/55958261/122520037-275e1300-cfe1-11eb-8e44-6b4a7aa62770.png)
